/**
 * context.js — ExecutionContext: SINGLE source of truth for pipeline execution identity
 *
 * CRITICAL SYSTEM MODULE
 * Created ONCE per run().
 * Passed by reference everywhere.
 * NEVER regenerated downstream.
 *
 * @module context
 */

import { execSync } from "child_process";

// ── Internal helper ─────────────────────────────────────────────────────────

function getGitCommit() {
  try {
    return execSync("git rev-parse --short HEAD", { encoding: "utf-8" }).trim();
  } catch {
    return "unknown";
  }
}

// ── Public API ──────────────────────────────────────────────────────────────

/**
 * Create a single ExecutionContext for a pipeline run.
 *
 * Must be called EXACTLY ONCE per run() invocation.
 * The returned ctx object is the ONLY source of identity downstream.
 *
 * @param {object} params
 * @param {string} params.runId       - Unique run identifier (MUST be generated by caller)
 * @param {string} [params.job]       - Job name (default: "daily-newsletter")
 * @param {string} [params.webhookUrl] - Apps Script webhook URL
 * @returns {ExecutionContext} The immutable execution context
 */
export function createExecutionContext({ runId, job, webhookUrl }) {
  if (!runId) {
    throw new Error("[CONTEXT] Cannot create ExecutionContext without runId");
  }

  const ctx = {
    // ── Identity (IMMUTABLE) ───────────────────────────────────────────
    runId,                    // ONLY source of identity — no fallbacks, no regeneration
    job: job || "daily-newsletter",
    startedAt: Date.now(),

    // ── Pipeline State ─────────────────────────────────────────────────
    state: {
      status: "RUNNING",
      stage: null,
      failedAt: null,
      failedReason: null,
    },

    // ── Agent State (written by agent-orchestrator) ────────────────────
    agents: {
      macro: "pending",
      gcc: "pending",
      risk: "pending",
      editor: "pending",
    },

    // ── Truth State (written by truth-evaluator) ───────────────────────
    truth: {
      git: false,
      appsScript: false,
      email: false,
      score: 0,
      verifiedState: null,
      mismatch: false,
    },

    // ── Metadata (immutable after creation) ────────────────────────────
    metadata: {
      gitCommit: getGitCommit(),
      env: process.env.NODE_ENV || "development",
      webhookUrl: webhookUrl || null,
    },
  };

  return ctx;
}

export default {
  createExecutionContext,
};
